-- Add volunteer AuditAction enum values (safe — already exist in schema from SCHEMA-002)
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VOLUNTEER_PROFILE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VOLUNTEER_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VOLUNTEER_REJECTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VOLUNTEER_ASSIGNED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VOLUNTEER_CHECKED_IN';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VOLUNTEER_CHECKED_OUT';

-- Add volunteer EmailTemplateType enum values
ALTER TYPE "EmailTemplateType" ADD VALUE IF NOT EXISTS 'VOLUNTEER_REQUEST_RECEIVED';
ALTER TYPE "EmailTemplateType" ADD VALUE IF NOT EXISTS 'VOLUNTEER_REQUEST_NOTIFY';
